version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build_dependencies:
    docker:
      - image: circleci/node:14.15
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - ~/repo/node_modules
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: node_modules
  test_app:
    docker:
      - image: circleci/node:14.15
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Format
          command: yarn format:check
      - run:
          name: Coverage
          command: yarn coverage
      - run:
          name: Codecov
          command: codecov
workflows:
  build_app:
    jobs:
      - build_dependencies
      - test_app:
          requires:
            - build_dependencies
